server:
  port: 8080
  servlet:
    context-path: /weatherApp

      
openweather:
  api:
    key: 14a1c7f054fe63e40ccd264acd2353fa
    baseurl: http://api.openweathermap.org/data/2.5
  forecast:
    url: ${openweather.api.baseurl}/forecast?q={city},{country}&APPID={key}
  weather:
    url: ${openweather.api.baseurl}/weather?q={city},{country}&APPID={key}&units=metric
    
springdoc:
  pathsToMatch: /**
  api-docs:
    path: /openapi/v3/docs
  swagger-ui:
    path: /openapi/swagger-ui
